### ISSUE TITLE
HE Algorithm reference

### ISSUE THREAD

**Issue by ZinuoCai** [MarzioMonticelli/python-cryptonet#1]
Hey! I have read your report carefully because it gives me a clear explanation of your implementation. I have a question of the HE algorithm. Can you provide some reference of the HE algorithm utilized in your report? Thanks!

**Comment by MarzioMonticelli** [comment]
To have more information on the used Homomorphic Encryption algorithm I invite you to read the documentation from the official **SEAL** library you can found [here](https://github.com/Microsoft/SEAL). On the other hand if you need to know how the library was inherited you can read more about it in the [Pyfhel official repository](https://github.com/ibarrond/Pyfhel). To have even more specific information on the HE algorithm I highly recommend you to read this **awesome** [paper](https://eprint.iacr.org/2012/144.pdf) from Junfeng Fan and Frederik Vercauteren.
I apologize for the late reply. Let me know if you have found everything you need. Cheers.
